### ISSUE TITLE
[BUG] The `**.<ext>` pattern matches only files from the root (= `*.<ext>`)

### ISSUE THREAD

**Issue by jond01** [tj-actions/glob#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

As the title says, I'm using the `tj-actions/glob` action (indirectly, via `tj-actions/changed-files`) with the following pattern:

```yaml
- uses: tj-actions/glob@v16.8
  id: glob-all-js
  with:
    files: |
      **.js
```

With the following tree structure:
```text
.
├── .github
│   └── workflows
│       └── glob.yml
├── README.md
├── index.js
├── js
│   └── index.js
└── src
    └── js
        └── app.js
```

But the output of the glob action is only the `index.js` file from the root:
https://github.com/jond01/tj-actions-glob-example/actions/runs/3892727375/jobs/6644480436#step:4:5

### To Reproduce

https://github.com/jond01/tj-actions-glob-example

Run the workflow via the "Actions" tab.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expect all the `.js` files to be listed, as also explained on GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

> `'**.js'`
>
> Matches all `.js` files in the repository.
>
> `index.js`
>
> `js/index.js`
>
> `src/js/app.js`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@jond01 I believe that’s a know limitation and has been highlighted in the docs.

Please refer to the [Usage](https://github.com/tj-actions/glob#usage) section for more information.

**Comment by jond01** [comment]
Ok, thanks for clarifying it in fb6a49f21653eca6ecb9111fa816188a37a1affd.

Still, I suggest not using this pattern in the first example (quite misleading IMO):

```yaml
...
    steps:
      - uses: actions/checkout@v2

      - name: Glob match
        uses: tj-actions/glob@v16
        id: glob
        with:
          files: |
            *.md
            **.yaml
            **.yml
            !action.yml
            **/rebase.yml

      - name: Show all matching files
        run: |
          echo "${{ steps.glob.outputs.paths }}"
        # Outputs: .github/workflows/rebase.yml .github/workflows/sync-release-version.yml .github/workflows/test.yml...
```
https://github.com/tj-actions/glob/tree/fb6a49f21653eca6ecb9111fa816188a37a1affd#usage
