### ISSUE TITLE
[Feature] Option to succeed if no path match the pattern

### ISSUE THREAD

**Issue by kftsehk** [tj-actions/glob#744]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Use case:

When configuring organization level action, it might happen that some repos using it might not need all the checks now (possibly it may eventually need).

E.g. Maybe this repo doesn't use SQL now, but it is possible that eventually it will need one too, as the repo develop.

```yaml
jobs:
  schema:
    name: Check sql files
    runs-on: ubuntu-latest
    steps:
      - id: changed-files
        name: Get changed schema
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.sql
     # ...
```

This currently fail with

```
/usr/bin/git diff --diff-filter=D --name-only <hash1>...<hash2>
Error: No paths found using the specified patterns
```

### Describe the solution you'd like?

```yaml
jobs:
  schema:
    name: Check sql files
    runs-on: ubuntu-latest
    steps:
      - id: changed-files
        name: Get changed schema
        uses: tj-actions/changed-files@v35
        with:
          allow_no_file_match: true
          files: |
            **/*.sql
```

Which will still shows a warning but is considered success
Since there is no file matching the pattern, it is not possible something can change, thus it should return same output as nothing changed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
